#!/bin/sh
#######################################################
#						                              #
#     Split data file into training and test set      #
#     arguments are				                      #
#          base file name,			                  #
#          number of instances for training file      #
#          suffix for naming the training/test files  #
#						                              #
#     assumes that the data file is <base>.data	      #
#     and that the first two lines are header         #
#######################################################


if [ "$1" = "" ] ; then
   echo "usage split-datafile filebasename size-of-training [suffix]"
   exit
fi

if [ ! -e "$1.data" ] ; then 
   echo $1.data does not exist
   exit
fi

if [ "$2" = "" ] ; then
   echo "usage split-datafile filebasename size-of-training [suffix]"
   echo "must specify the number of instances for training set (up to $(wc -l $1.dat))"
   exit
fi

if [ $2 -gt $(($(cat "$1.data"|wc -l)-2)) ] ; then
   echo "usage split-datafile filebasename size-of-training \[suffix\]"
   echo only $(($(cat "$1.data"|wc -l)-2)) instances in training set
   exit
fi

if [ "$3" = "" ] ; then
   suffix=""
else
   suffix="-$3"
fi

tempdata="/tmp/$$.$1"

cat $1.data |tail +3 |shuffle -f - > $tempdata

head -2 $1.data > $1-training${suffix}.data
head -$2 $tempdata >> $1-training${suffix}.data

head -2 $1.data > $1-test${suffix}.data
tail +$(($2+1)) $tempdata >> $1-test${suffix}.data

rm $tempdata

echo created $1-training${suffix}.data and $1-test${suffix}.data

